const appointmentMock: appointmentType[] = [
	{
		appointmentId: "1001",
		name: "Consulta Adrian Fachi nº 1",
		date: new Date(2025, 10, 24),
		startsAt: new Date(),
		endsAt: new Date(),
	},
	{
		appointmentId: "1002",
		name: "Consulta B",
		date: new Date(2025, 10, 25),
		startsAt: new Date(),
		endsAt: new Date(),
	},
	{
		appointmentId: "1003",
		name: "Consulta C",
		date: new Date(2025, 10, 25),
		startsAt: new Date(),
		endsAt: new Date(),
	},
	{
		appointmentId: "1004",
		name: "Consulta D",
		date: new Date(2025, 10, 27),
		startsAt: new Date(),
		endsAt: new Date(),
	},
	{
		appointmentId: "1005",
		name: "Consulta E",
		date: new Date(2025, 10, 28),
		startsAt: new Date(),
		endsAt: new Date(),
	},
	{
		appointmentId: "1006",
		name: "Consulta F",
		date: new Date(2025, 10, 30),
		startsAt: new Date(),
		endsAt: new Date(),
	},

	// Dezembro
	{
		appointmentId: "1007",
		name: "Consulta G",
		date: new Date(2025, 11, 1),
		startsAt: new Date(),
		endsAt: new Date(),
	},
	{
		appointmentId: "1008",
		name: "Consulta H",
		date: new Date(2025, 11, 2),
		startsAt: new Date(),
		endsAt: new Date(),
	},
	{
		appointmentId: "1009",
		name: "Consulta I",
		date: new Date(2025, 11, 3),
		startsAt: new Date(),
		endsAt: new Date(),
	},
	{
		appointmentId: "1010",
		name: "Consulta J",
		date: new Date(2025, 11, 5),
		startsAt: new Date(),
		endsAt: new Date(),
	},
	{
		appointmentId: "1011",
		name: "Consulta K",
		date: new Date(2025, 11, 10),
		startsAt: new Date(),
		endsAt: new Date(),
	},
	{
		appointmentId: "1012",
		name: "Consulta L",
		date: new Date(2025, 11, 10),
		startsAt: new Date(),
		endsAt: new Date(),
	},
	{
		appointmentId: "1013",
		name: "Consulta M",
		date: new Date(2025, 11, 15),
		startsAt: new Date(),
		endsAt: new Date(),
	},
	{
		appointmentId: "1014",
		name: "Consulta N",
		date: new Date(2025, 11, 20),
		startsAt: new Date(),
		endsAt: new Date(),
	},
	{
		appointmentId: "1015",
		name: "Consulta O",
		date: new Date(2025, 11, 24),
		startsAt: new Date(),
		endsAt: new Date(),
	},
	{
		appointmentId: "1016",
		name: "Consulta P",
		date: new Date(2025, 11, 26),
		startsAt: new Date(),
		endsAt: new Date(),
	},
	{
		appointmentId: "1017",
		name: "Consulta Q",
		date: new Date(2025, 11, 28),
		startsAt: new Date(),
		endsAt: new Date(),
	},
	{
		appointmentId: "1018",
		name: "Consulta R",
		date: new Date(2025, 11, 29),
		startsAt: new Date(),
		endsAt: new Date(),
	},
	{
		appointmentId: "1019",
		name: "Consulta S",
		date: new Date(2025, 11, 30),
		startsAt: new Date(),
		endsAt: new Date(),
	},
];

export default appointmentMock;
