import appointmentTest from "./appointmentTest";

const patientTest: patientType[] = [
	{
		patientId: 1,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Adão Louco",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
	{
		patientId: 2,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Adão Louco",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
	{
		patientId: 3,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Adão Louco",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
	{
		patientId: 4,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Adão Louco",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
	{
		patientId: 5,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Lorenzo Ali Gonçalves de Brito Castelo",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
	{
		patientId: 6,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Adão Louco",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
	{
		patientId: 7,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Adão Louco",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
	{
		patientId: 8,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Adão Louco",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
	{
		patientId: 9,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Adão Louco",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
	{
		patientId: 10,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Lorenzo Ali Gonçalves de Brito Castelo",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
	{
		patientId: 11,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Adão Louco",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
	{
		patientId: 12,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Adão Louco",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
	{
		patientId: 13,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Adão Louco",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
	{
		patientId: 14,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Adão Louco",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
	{
		patientId: 15,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Lorenzo Ali Gonçalves de Brito Castelo",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
	{
		patientId: 16,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Adão Louco",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
	{
		patientId: 17,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Adão Louco",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
	{
		patientId: 18,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Adão Louco",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
	{
		patientId: 19,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Adão Louco",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
	{
		patientId: 20,
		email: "teste@teste.com",
		cpf: "12345678900",
		name: "Lorenzo Ali Gonçalves de Brito Castelo",
		telephone: "51996105286",
		birth: new Date(),
		occupation: "Doutor",
		origin: "amigo",
		first_appointment: new Date(),
		recurrence: "mensal",
		createdAt: new Date(),
		updateAt: new Date(),
		appointment: appointmentTest,
	},
];

export default patientTest;
